// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Uam.LabHelpDesk.Api.Data;

#nullable disable

namespace Uam.LabHelpDesk.Api.Data.Migrations
{
    [DbContext(typeof(AppDbContext))]
    partial class AppDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "10.0.7")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("Uam.LabHelpDesk.Api.Models.Laboratory", b =>
            {
                b.Property<int>("Id")
                    .ValueGeneratedOnAdd()
                    .HasColumnType("int");
                SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                b.Property<string>("Name")
                    .IsRequired()
                    .HasMaxLength(100)
                    .HasColumnType("nvarchar(100)");

                b.Property<string>("Building")
                    .IsRequired()
                    .HasMaxLength(50)
                    .HasColumnType("nvarchar(50)");

                b.Property<int>("Floor")
                    .HasColumnType("int");

                b.Property<int>("Capacity")
                    .HasColumnType("int");

                b.Property<bool>("IsActive")
                    .HasDefaultValue(true)
                    .HasColumnType("bit");

                b.Property<DateTime>("CreatedAtUtc")
                    .HasColumnType("datetime2");

                b.Property<DateTime>("UpdatedAtUtc")
                    .HasColumnType("datetime2");

                b.HasKey("Id");
                b.HasIndex("Name").IsUnique();
                b.ToTable("Laboratories");
            });

            modelBuilder.Entity("Uam.LabHelpDesk.Api.Models.Equipment", b =>
            {
                b.Property<int>("Id")
                    .ValueGeneratedOnAdd()
                    .HasColumnType("int");
                SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                b.Property<int>("LaboratoryId")
                    .HasColumnType("int");

                b.Property<string>("Code")
                    .IsRequired()
                    .HasMaxLength(20)
                    .HasColumnType("nvarchar(20)");

                b.Property<string>("Brand")
                    .IsRequired()
                    .HasMaxLength(50)
                    .HasColumnType("nvarchar(50)");

                b.Property<string>("Model")
                    .IsRequired()
                    .HasMaxLength(50)
                    .HasColumnType("nvarchar(50)");

                b.Property<string>("SerialNumber")
                    .IsRequired()
                    .HasMaxLength(50)
                    .HasColumnType("nvarchar(50)");

                b.Property<string>("Type")
                    .IsRequired()
                    .HasMaxLength(30)
                    .HasColumnType("nvarchar(30)");

                b.Property<string>("Status")
                    .IsRequired()
                    .HasMaxLength(20)
                    .HasColumnType("nvarchar(20)");

                b.Property<DateOnly?>("PurchaseDate")
                    .HasColumnType("date");

                b.Property<bool>("IsActive")
                    .HasDefaultValue(true)
                    .HasColumnType("bit");

                b.Property<DateTime>("CreatedAtUtc")
                    .HasColumnType("datetime2");

                b.Property<DateTime>("UpdatedAtUtc")
                    .HasColumnType("datetime2");

                b.HasKey("Id");
                b.HasIndex("Code").IsUnique();
                b.HasIndex("SerialNumber").IsUnique();
                b.HasIndex("LaboratoryId");
                b.ToTable("Equipment");
            });

            modelBuilder.Entity("Uam.LabHelpDesk.Api.Models.Equipment", b =>
            {
                b.HasOne("Uam.LabHelpDesk.Api.Models.Laboratory", "Laboratory")
                    .WithMany("Equipments")
                    .HasForeignKey("LaboratoryId")
                    .OnDelete(DeleteBehavior.Restrict)
                    .IsRequired();
                b.Navigation("Laboratory");
            });

            modelBuilder.Entity("Uam.LabHelpDesk.Api.Models.Laboratory", b =>
            {
                b.Navigation("Equipments");
            });
#pragma warning restore 612, 618
        }
    }
}
